import { WasteListing, GreenOfficerReport, RewardCard, SensorMarker, AuditLogEntry } from '@/types';

export const INITIAL_LISTINGS: WasteListing[] = [
  {
    id: 'req-01',
    transactionId: 'TXN-884291',
    userId: 'usr-101',
    userName: 'Badal',
    userPhone: '+91 98201 44556',
    title: 'Mechanical Gaming Keyboard & Wireless Mouse',
    description: 'Working RGB mechanical keyboard with blue switches and optical mouse with degraded battery.',
    category: 'IT Product',
    wasteTypeTag: 'IT Product — E-Waste / High Value',
    imageUrl: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=600&q=80',
    calculatedCredits: 85,
    estimatedWeightKg: 1.4,
    senderLocation: 'Bandra West, Mumbai, India',
    status: 'PENDING',
    createdAt: Date.now() - 1000 * 60 * 35,
  },
  {
    id: 'req-02',
    transactionId: 'TXN-912044',
    userId: 'usr-102',
    userName: 'Tanvir Habib Laskar',
    userPhone: '+91 94350 78219',
    title: 'Double-Door Frost Free Refrigerator',
    description: 'Compressor functional, cabinet replaced due to kitchen remodel. Heavy steel housing.',
    category: 'Electronic Waste',
    wasteTypeTag: 'Electronic Waste — E-Waste / Heavy Metal',
    imageUrl: 'https://images.unsplash.com/photo-1571175443880-49e1d25b2bc5?auto=format&fit=crop&w=600&q=80',
    calculatedCredits: 160,
    estimatedWeightKg: 52.0,
    senderLocation: 'Silchar, Assam, India',
    status: 'PENDING',
    createdAt: Date.now() - 1000 * 60 * 80,
  },
  {
    id: 'req-03',
    transactionId: 'TXN-742103',
    userId: 'usr-103',
    userName: 'Vyom Srivastava',
    userPhone: '+91 91510 88234',
    title: 'Vintage Commuter Bicycle with Alloy Rims',
    description: 'Flat tires and surface rust on chain, aluminum 6061 frame intact and suitable for smelting.',
    category: 'Transport',
    wasteTypeTag: 'Transport — Recyclable Bulk Metal',
    imageUrl: 'https://images.unsplash.com/photo-1485965120184-e220f721d03e?auto=format&fit=crop&w=600&q=80',
    calculatedCredits: 120,
    estimatedWeightKg: 13.2,
    senderLocation: 'Gomti Nagar, Lucknow, India',
    status: 'PENDING',
    createdAt: Date.now() - 1000 * 60 * 120,
  },
  {
    id: 'req-04',
    transactionId: 'TXN-553199',
    userId: 'usr-104',
    userName: 'Priya Sharma',
    userPhone: '+91 98765 43210',
    title: 'Solid Teak Wood Study Desk & Ergonomic Chair',
    description: 'Reclaimed teak wood tabletop and adjustable swivel frame.',
    category: 'Furniture',
    wasteTypeTag: 'Furniture — Bulky Dry Waste',
    imageUrl: 'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?auto=format&fit=crop&w=600&q=80',
    calculatedCredits: 95,
    estimatedWeightKg: 26.0,
    senderLocation: 'Indiranagar 100ft Road, Bangalore',
    status: 'PENDING',
    createdAt: Date.now() - 1000 * 60 * 240,
  },
  {
    id: 'req-05',
    transactionId: 'TXN-321980',
    userId: 'usr-105',
    userName: 'Sofia Rossi',
    userPhone: '+39 06 6987 1234',
    title: 'Flint Glass Containers & Beverage Bottles (18 count)',
    description: 'Clean, sanitized clear glass culinary jars and beverage bottles.',
    category: 'Glass Product',
    wasteTypeTag: 'Glass Product — Dry Waste',
    imageUrl: 'https://images.unsplash.com/photo-1527061011665-3652c757a4d4?auto=format&fit=crop&w=600&q=80',
    calculatedCredits: 50,
    estimatedWeightKg: 7.5,
    senderLocation: 'Via del Corso 12, District 3',
    status: 'ACCEPTED',
    assignedDeliveryAgent: 'Vikram Singh (Eco Courier #42)',
    estimatedPickupTime: 'Today, 4:30 PM - 5:30 PM',
    createdAt: Date.now() - 1000 * 60 * 360,
  }
];

export const INITIAL_REWARDS: RewardCard[] = [
  {
    id: 'rew-01',
    provider: 'Amazon',
    title: 'Amazon Eco Gift Card',
    creditsRequired: 150,
    voucherCode: 'AMZ-ECO-7789-9921',
    discountAmount: '₹500 / $10 Voucher',
    imageUrl: 'https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?auto=format&fit=crop&w=400&q=80',
    description: 'Instant Amazon Pay gift code redeemable on all sustainable and eco-friendly catalog items.'
  },
  {
    id: 'rew-02',
    provider: 'Flipkart',
    title: 'Flipkart Green SuperCoin Card',
    creditsRequired: 120,
    voucherCode: 'FLP-GRN-4421-5509',
    discountAmount: '₹400 Instant Cashback',
    imageUrl: 'https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?auto=format&fit=crop&w=400&q=80',
    description: 'Redeem across Flipkart electronics exchange program or sustainable consumer goods.'
  },
  {
    id: 'rew-03',
    provider: 'Google Play',
    title: 'Google Play Store Recharge',
    creditsRequired: 90,
    voucherCode: 'GPLY-2938-PL99-4412',
    discountAmount: '₹250 Digital Credit',
    imageUrl: 'https://images.unsplash.com/photo-1616469829941-c7200edec809?auto=format&fit=crop&w=400&q=80',
    description: 'Direct Google Play account balance for apps, climate science e-books, and media subscriptions.'
  },
  {
    id: 'rew-04',
    provider: 'Starbucks Eco',
    title: 'Starbucks Zero-Cup Eco Voucher',
    creditsRequired: 60,
    voucherCode: 'SBUX-ZERO-9941-88',
    discountAmount: 'Free Artisan Beverage',
    imageUrl: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=400&q=80',
    description: 'Claim a handcrafted zero-waste drink when bringing your personal reusable tumbler.'
  }
];

export const INITIAL_REPORTS: GreenOfficerReport[] = [
  {
    id: 'rep-01',
    officerName: 'Elena Rostova (Green Officer #12)',
    locationName: 'Central Metro Plaza Restroom',
    city: 'Copenhagen',
    lat: 55.6761,
    lng: 12.5683,
    facilityType: 'Restroom',
    photoUrl: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=500&q=80',
    rating: 2,
    crowdLevel: 'High',
    cleanlinessState: 'Needs Attention',
    missingDustbins: true,
    notes: 'Sanitizer dispenser depleted, automated flush valve sensor lagging during peak commuter hours.',
    status: 'REPORTED',
    timestamp: Date.now() - 1000 * 60 * 40,
  },
  {
    id: 'rep-02',
    officerName: 'Tariq Al-Mansoor (Officer #09)',
    locationName: 'City Botanical Water Refill Station',
    city: 'Copenhagen',
    lat: 55.6841,
    lng: 12.5710,
    facilityType: 'Water Source',
    photoUrl: 'https://images.unsplash.com/photo-1548839140-29a749e1bc4e?auto=format&fit=crop&w=500&q=80',
    rating: 4,
    crowdLevel: 'Low',
    cleanlinessState: 'Spotless',
    missingDustbins: false,
    notes: 'Purified mineral water pressure optimal, TDS reading tested at 68 ppm. Very clean.',
    status: 'RESOLVED',
    timestamp: Date.now() - 1000 * 60 * 180,
    resolvedAt: Date.now() - 1000 * 60 * 30,
  },
  {
    id: 'rep-03',
    officerName: 'Ananya Deshmukh (Officer #27)',
    locationName: 'Indre By Public Boulevard Recycling Hub',
    city: 'Copenhagen',
    lat: 55.6795,
    lng: 12.5830,
    facilityType: 'Dustbin',
    photoUrl: 'https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?auto=format&fit=crop&w=500&q=80',
    rating: 1,
    crowdLevel: 'High',
    cleanlinessState: 'Critical',
    missingDustbins: true,
    notes: 'Severe overflow of beverage cartons around tourist zone. Urgent municipal compaction truck required.',
    status: 'REPORTED',
    timestamp: Date.now() - 1000 * 60 * 15,
  }
];

export const INITIAL_SENSORS: SensorMarker[] = [
  {
    id: 'sns-01',
    code: 'CPH-SEN-00342',
    name: 'Norreport Hub Smart Pole #14',
    type: 'Sensor Pole',
    lat: 55.6833,
    lng: 12.5716,
    status: 'Connected',
    fillLevel: 34,
    cleanlinessScore: 92,
    crowdLevel: 'Moderate',
    lastUpdated: '2 mins ago',
    alertsCount: 0,
    details: {
      airQuality: 'AQI 28 (Good)',
      temperature: '18.4°C',
      waterPurity: '99.2%',
      batteryLevel: '94% Solar',
    }
  },
  {
    id: 'sns-02',
    code: 'CPH-TOI-00108',
    name: 'Amalienborg Public Sanitation Unit',
    type: 'Toilet',
    lat: 55.6840,
    lng: 12.5930,
    status: 'Connected',
    fillLevel: 45,
    cleanlinessScore: 88,
    crowdLevel: 'Low',
    lastUpdated: '5 mins ago',
    alertsCount: 0,
    details: {
      airQuality: 'AQI 32 (Good)',
      temperature: '20.1°C',
      waterPurity: '98.7%',
      batteryLevel: '89%',
    }
  },
  {
    id: 'sns-03',
    code: 'CPH-BIN-00561',
    name: 'Christiansborg Quad Compactor Bin',
    type: 'Bin',
    lat: 55.6761,
    lng: 12.5806,
    status: 'Warning',
    fillLevel: 89,
    cleanlinessScore: 42,
    crowdLevel: 'High',
    lastUpdated: 'Just now',
    alertsCount: 2,
    details: {
      airQuality: 'AQI 54 (Moderate)',
      temperature: '21.0°C',
      waterPurity: 'N/A',
      batteryLevel: '68%',
    }
  },
  {
    id: 'sns-04',
    code: 'CPH-WTR-00219',
    name: 'Kongens Nytorv Hydration Oasis',
    type: 'Water',
    lat: 55.6805,
    lng: 12.5860,
    status: 'Connected',
    fillLevel: 12,
    cleanlinessScore: 96,
    crowdLevel: 'Moderate',
    lastUpdated: '1 min ago',
    alertsCount: 0,
    details: {
      airQuality: 'AQI 22 (Optimal)',
      temperature: '17.8°C',
      waterPurity: '99.9%',
      batteryLevel: '98% Solar',
    }
  },
  {
    id: 'sns-05',
    code: 'CPH-BIN-00994',
    name: 'Vesterbro Eco-Pod Array',
    type: 'Bin',
    lat: 55.6690,
    lng: 12.5520,
    status: 'Disconnected',
    fillLevel: 98,
    cleanlinessScore: 24,
    crowdLevel: 'High',
    lastUpdated: '38 mins ago',
    alertsCount: 4,
    details: {
      airQuality: 'AQI 68 (Alert)',
      temperature: '23.5°C',
      waterPurity: 'N/A',
      batteryLevel: '12% Critical',
    }
  }
];

export const INITIAL_AUDIT_LOGS: AuditLogEntry[] = [
  {
    id: 'aud-01',
    action: 'Compaction cycle triggered & bin emptied',
    target: 'Christiansborg Quad Compactor #561',
    city: 'Copenhagen',
    performedBy: 'Autonomous Municipal Unit #08',
    timestamp: '10 mins ago',
    status: 'Resolved'
  },
  {
    id: 'aud-02',
    action: 'Sanitization refill dispatched',
    target: 'Central Metro Plaza Restroom',
    city: 'Copenhagen',
    performedBy: 'Rapid Response Team Alpha',
    timestamp: '25 mins ago',
    status: 'In Process'
  },
  {
    id: 'aud-03',
    action: 'IoT telemetry restored',
    target: 'Kongens Nytorv Hydration Oasis #219',
    city: 'Copenhagen',
    performedBy: 'Smart Grid Ops',
    timestamp: '1 hour ago',
    status: 'Resolved'
  },
  {
    id: 'aud-04',
    action: 'Sensor malfunction inspection scheduled',
    target: 'Vesterbro Eco-Pod Array #994',
    city: 'Copenhagen',
    performedBy: 'Officer Ananya Deshmukh',
    timestamp: '2 hours ago',
    status: 'Under Review'
  }
];
